### ISSUE TITLE
Lasciare una nota nella creazione dei passaggi (o nella ricerca come passeggero)

### ISSUE THREAD

**Issue by maxiride** [kercos/PickMeUp#10]
Nella creazione di un passaggio (o nella ricerca come passeggero) dare la possibilità di lasciare una breve nota. 
Ad esempio da dove si parte esattamente, o dove ci si trova, come si è vestito o che macchina si ha per essere riconosciuti.

**Comment by kercos** [comment]
Aggiunto la possibilità per l'autista di mandare messaggi ai passeggeri una volta selezionata la partenza e l'orario di arrivo previsto.
